// symptoms_categorization.dart

class Symptom {
  final String name;
  final List<String>? subSymptoms;

  Symptom(this.name, [this.subSymptoms]);
}

final List<Symptom> symptoms = [
  Symptom('General Symptoms', [
    'Fever',
    'Fatigue',
    'Headache',
    'Chills',
    'Sweating',
    'Weight Loss',
    'Weight Gain',
    'Malaise',
    'Weakness',
    'Dizziness',
    'Nausea',
    'Vomiting',
    'Feeling Ill',
    'Recent Weight Loss',
    'Sleepiness',
    'Restlessness',
    'Ache All Over',
  ]),
  Symptom('Breathing Issues', [
    'Shortness Of Breath',
    'Sharp Chest Pain',
    'Chest Tightness',
    'Cough',
    'Breathing Fast',
    'Wheezing',
    'Hoarse Voice',
    'Sore Throat',
    'Difficulty Speaking',
    'Throat Swelling',
    'Nasal Congestion',
    'Congestion In Chest',
    'Coughing Up Sputum',
    'Hurts To Breath',
    'Abnormal Breathing Sounds',
    'Difficulty Breathing',
  ]),
  Symptom('Heart & Blood', [
    'Palpitations',
    'Irregular Heartbeat',
    'Increased Heart Rate',
    'Decreased Heart Rate',
    'Fainting',
    'Peripheral Edema',
    'Heartburn',
    'Flushing',
    'Chest Discomfort',
    'Rib Pain',
  ]),
  Symptom('Stomach & Digestion', [
    'Abdominal Pain',
    'Sharp Abdominal Pain',
    'Burning Abdominal Pain',
    'Flatulence',
    'Vomiting',
    'Nausea',
    'Diarrhea',
    'Constipation',
    'Blood In Stool',
    'Vomiting Blood',
    'Regurgitation',
    'Stomach Bloating',
    'Lower Abdominal Pain',
    'Swollen Abdomen',
    'Abdominal Distention',
  ]),
  Symptom('Brain & Nerves', [
    'Dizziness',
    'Insomnia',
    'Seizures',
    'Headache',
    'Fainting',
    'Memory Loss',
    'Confusion',
    'Slurring Words',
    'Tremors',
    'Disturbance Of Memory',
    'Paresthesia',
    'Side Pain',
    'Restlessness',
  ]),
  Symptom('Bones & Muscles', [
    'Leg Pain',
    'Back Pain',
    'Neck Pain',
    'Hip Pain',
    'Arm Pain',
    'Joint Pain',
    'Muscle Pain',
    'Muscle Cramps',
    'Muscle Weakness',
    'Stiffness',
    'Lower Back Cramps Or Spasms',
    'Shoulder Pain',
    'Knee Pain',
    'Foot Or Toe Pain',
    'Hand Or Finger Pain',
  ]),
  Symptom('Skin Symptoms', [
    'Skin Swelling',
    'Dry Lips',
    'Acne Or Pimples',
    'Skin Lesion',
    'Skin Rash',
    'Red Spots',
    'Itching',
    'Peeling Skin',
    'Ulcers',
    'Skin Discoloration',
    'Skin Growth',
    'Itchy Scalp',
    'Wrinkles On Skin',
    'Skin Irritation',
    'Bumps On Penis',
  ]),
  Symptom('Urinary Symptoms', [
    'Retention Of Urine',
    'Frequent Urination',
    'Painful Urination',
    'Blood In Urine',
    'Involuntary Urination',
    'Low Urine Output',
    'Cloudy Urine',
    'Urgency To Urinate',
  ]),
  Symptom('Reproductive Symptoms', [
    'Pelvic Pain',
    'Vaginal Itching',
    'Vaginal Dryness',
    'Vaginal Discharge',
    'Vaginal Pain',
    'Pain During Intercourse',
    'Bleeding Or Discharge From Nipple',
    'Infertility',
    'Scanty Menstrual Flow',
    'Irregular Periods',
    'Heavy Menstrual Flow',
    'Spotting Or Bleeding During Pregnancy',
    'Premature Ejaculation',
  ]),
  Symptom('Eye Symptoms', [
    'Pain In Eye',
    'Double Vision',
    'Diminished Vision',
    'Eye Redness',
    'Itchiness Of Eye',
    'Spots Or Clouds In Vision',
    'Lacrimation',
    'Eye Deviation',
    'Foreign Body Sensation In Eye',
    'Eye Burns Or Stings',
    'Swollen Eye',
    'Mass On Eyelid',
  ]),
  Symptom('Mental Health Symptoms', [
    'Anxiety And Nervousness',
    'Depression',
    'Emotional Symptoms',
    'Excessive Anger',
    'Hostile Behavior',
    'Hysterical Behavior',
  ]),
  Symptom('Other Symptoms', [
    'Drug Abuse',
    'Alcohol Abuse',
    'Feeling Hot',
    'Feeling Cold',
    'Night Sweats',
    'Cold Hands And Feet',
    'Sleepiness',
    'Excessive Appetite',
    'Decreased Appetite',
  ]),
];
