// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABUSlP3tGxabaFlt9EB1IPAXAyFxDjPFg',
    appId: '1:852822518412:web:7b7456bf8f7983dce769a9',
    messagingSenderId: '852822518412',
    projectId: 'healthapp-ecd69',
    authDomain: 'healthapp-ecd69.firebaseapp.com',
    storageBucket: 'healthapp-ecd69.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr2KYwu96nfgDqD9vkfWmas1XiRpKvX-c',
    appId: '1:852822518412:android:854797582051bc36e769a9',
    messagingSenderId: '852822518412',
    projectId: 'healthapp-ecd69',
    storageBucket: 'healthapp-ecd69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCTX6AFgsZD4lLdoh1sbpscm-RTTSFgY8',
    appId: '1:852822518412:ios:85622df1ee0177e1e769a9',
    messagingSenderId: '852822518412',
    projectId: 'healthapp-ecd69',
    storageBucket: 'healthapp-ecd69.appspot.com',
    iosBundleId: 'com.example.healthapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCTX6AFgsZD4lLdoh1sbpscm-RTTSFgY8',
    appId: '1:852822518412:ios:85622df1ee0177e1e769a9',
    messagingSenderId: '852822518412',
    projectId: 'healthapp-ecd69',
    storageBucket: 'healthapp-ecd69.appspot.com',
    iosBundleId: 'com.example.healthapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABUSlP3tGxabaFlt9EB1IPAXAyFxDjPFg',
    appId: '1:852822518412:web:ccfe97763d5b4f3fe769a9',
    messagingSenderId: '852822518412',
    projectId: 'healthapp-ecd69',
    authDomain: 'healthapp-ecd69.firebaseapp.com',
    storageBucket: 'healthapp-ecd69.appspot.com',
  );

}